/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import javax.swing.ButtonGroup;

/**
 *
 * @author Maxwell
 */
public class fifth extends javax.swing.JFrame {

    /**
     * Creates new form fifth
     */
    
    private boolean radioText;
    
    public void buttonGroup(){
    ButtonGroup bg = new ButtonGroup();
    bg.add(car1);
    bg.add(car2);
    bg.add(car3);
    bg.add(car4);
    
    
    }
    public fifth() {
        initComponents();
        setVisible(true);
        setTitle("Additional Service");
        setSize(717, 480);
        setResizable(false);
        theCar.setVisible(false);
        theCarPrice.setVisible(false);
        buttonGroup();
        String radioText = "";
        if (car1.isSelected())
        {
            radioText = car1.getText();
        }
        if (car2.isSelected())
        {
            radioText = car2.getText();
        }
        if (car3.isSelected())
        {
            radioText = car3.getText();
        }
        if (car4.isSelected())
        {
            radioText = car4.getText();
        }
    }
    
    
    public void getData4(String t, String b, String g, String l, String m, String d, String y, String c, String cakechosed, String p, String a){
    
        double convTotal = Double.parseDouble(t);
        double convP = Double.parseDouble(p);
        double result = convP + convTotal;
        theTotal.setText(Double.toString(result));
        theBride.setText(b);
        theGroom.setText(g);
        location.setText(l);
        theMonth.setText(m);
        theDay.setText(d);
        theYear.setText(y);
        theSetChosed.setText(c);
        theCake.setText(cakechosed);
        theCakePrice.setText(p);
        thePerson.setText(a);
        
        theBride.setVisible(false);
        theGroom.setVisible(false);
        location.setVisible(false);
        theMonth.setVisible(false);
        theDay.setVisible(false);
        theYear.setVisible(false);
        theSetChosed.setVisible(false);
        theCake.setVisible(false);
        theCakePrice.setVisible(false);
        thePerson.setVisible(false);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theBride = new javax.swing.JLabel();
        theGroom = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        theMonth = new javax.swing.JLabel();
        theDay = new javax.swing.JLabel();
        theYear = new javax.swing.JLabel();
        theSetChosed = new javax.swing.JLabel();
        theCake = new javax.swing.JLabel();
        theCar = new javax.swing.JLabel();
        theCakePrice = new javax.swing.JLabel();
        car1 = new javax.swing.JRadioButton();
        car2 = new javax.swing.JRadioButton();
        car3 = new javax.swing.JRadioButton();
        car4 = new javax.swing.JRadioButton();
        theCarPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        theTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        thePerson = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        theBride.setText("bride");
        getContentPane().add(theBride);
        theBride.setBounds(40, 130, 24, 14);

        theGroom.setText("groom");
        getContentPane().add(theGroom);
        theGroom.setBounds(40, 150, 30, 14);

        location.setText("Location");
        getContentPane().add(location);
        location.setBounds(40, 170, 40, 14);

        theMonth.setText("month");
        getContentPane().add(theMonth);
        theMonth.setBounds(40, 190, 30, 14);

        theDay.setText("Day");
        getContentPane().add(theDay);
        theDay.setBounds(40, 210, 19, 14);

        theYear.setText("Year");
        getContentPane().add(theYear);
        theYear.setBounds(40, 230, 22, 14);

        theSetChosed.setText("Set Chosen");
        getContentPane().add(theSetChosed);
        theSetChosed.setBounds(40, 250, 80, 14);

        theCake.setText("Cake  Chosed");
        getContentPane().add(theCake);
        theCake.setBounds(40, 270, 90, 14);

        theCar.setText("Car");
        getContentPane().add(theCar);
        theCar.setBounds(40, 290, 17, 14);

        theCakePrice.setText("Cake Price");
        getContentPane().add(theCakePrice);
        theCakePrice.setBounds(40, 310, 80, 14);

        car1.setText("Bugatti Veyron 16.4 Grand Sport Vitesse Car");
        car1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car1ActionPerformed(evt);
            }
        });
        getContentPane().add(car1);
        car1.setBounds(190, 170, 250, 23);

        car2.setText("Lamborghini Aventador LP 750-4 SV");
        getContentPane().add(car2);
        car2.setBounds(450, 170, 210, 23);

        car3.setText("Ferrari Enzo");
        getContentPane().add(car3);
        car3.setBounds(260, 370, 93, 23);

        car4.setText("Chevrolet Camaro");
        car4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car4ActionPerformed(evt);
            }
        });
        getContentPane().add(car4);
        car4.setBounds(480, 380, 140, 23);

        theCarPrice.setText("Car Price");
        getContentPane().add(theCarPrice);
        theCarPrice.setBounds(40, 330, 70, 14);

        jLabel5.setText("P 50,000");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 200, 130, 14);

        jLabel7.setText("P 48,999");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 200, 70, 14);

        jLabel9.setText("P 47,999");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 390, 80, 14);

        jLabel14.setText("P 35, 999");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(480, 400, 90, 14);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 420, 73, 23);

        theTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        theTotal.setText("jLabel2");
        getContentPane().add(theTotal);
        theTotal.setBounds(80, 430, 180, 17);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\2017-chevrolet-camaro-2lt-coupe-angular-front.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 250, 230, 132);

        jLabel11.setText("Total:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 430, 34, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("P");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 430, 20, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\ferrari 458.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 250, 200, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/lambo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 10, 240, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/bugatti veyron.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 70, 210, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Additional Services");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 220, 20);

        thePerson.setText("Attendees");
        getContentPane().add(thePerson);
        thePerson.setBounds(40, 350, 80, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Car Rent");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 60, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/white-wallpapers-hd-24.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 720, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void car4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Final fin = new Final();
        this.setVisible(false);
        String t = theTotal.getText();
        String b = theBride.getText();
        String g = theGroom.getText();
        String l = location.getText();
        String m = theMonth.getText();
        String d = theDay.getText();
        String y = theYear.getText();
        String sc = theSetChosed.getText();
        String cake = theCake.getText();
        String cakeprice = theCakePrice.getText();
        String att = thePerson.getText();
        if(car1.isSelected()){
        theCar.setText("Bugatti Veyron 16.4 Grand Sport Vitesse Car");
        theCarPrice.setText("50000");
        }
        else if(car2.isSelected()){
        theCar.setText("Lamborghini Aventador LP 750-4 SV");
        theCarPrice.setText("48999");
        }
        else if(car3.isSelected()){
        theCar.setText("Ferrari Enzo");
        theCarPrice.setText("47999");
        }
        else if(car4.isSelected()){
        theCar.setText("Chevrolet Camaro");
        theCarPrice.setText("35999");
        }
        else{
        theCar.setText("None");
        theCarPrice.setText("0");}
        

        String car = theCar.getText();
        String carprice = theCarPrice.getText();
        fin.getData5(t, b, g, l, m, d, y, sc, cake, cakeprice, car, carprice, att);
        fin.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void car1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fifth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton car1;
    private javax.swing.JRadioButton car2;
    private javax.swing.JRadioButton car3;
    private javax.swing.JRadioButton car4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel location;
    private javax.swing.JLabel theBride;
    private javax.swing.JLabel theCake;
    private javax.swing.JLabel theCakePrice;
    private javax.swing.JLabel theCar;
    private javax.swing.JLabel theCarPrice;
    private javax.swing.JLabel theDay;
    private javax.swing.JLabel theGroom;
    private javax.swing.JLabel theMonth;
    private javax.swing.JLabel thePerson;
    private javax.swing.JLabel theSetChosed;
    private javax.swing.JLabel theTotal;
    private javax.swing.JLabel theYear;
    // End of variables declaration//GEN-END:variables
}
