/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form Final
     */
    public Final() {
        initComponents();
        setVisible(true);
        setTitle("Overview");
        setSize(717, 480);
        setResizable(false);
    }
    
    public void getData5(String t, String b, String g, String l, String m, String d, String y, String sc, String cake, String cakeprice, String car, String carprice, String att){
    double cpVal = Double.parseDouble(carprice);
    double totalVal = Double.parseDouble(t);
    double result = cpVal + totalVal;
    total.setText(Double.toString(result));
    loc.setText(l);
    theTwo.setText(b + " & " + g);
    theDate.setText(m + " " + d + ", " + y);
    foodset.setText(sc);
    theCake.setText(cake);
    carName.setText(car);
    attendeesNo.setText(att);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        carName = new javax.swing.JLabel();
        attendeesNo = new javax.swing.JLabel();
        theTwo = new javax.swing.JLabel();
        foodset = new javax.swing.JLabel();
        theDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        theCake = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setText("Attendees: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 190, 80, 14);

        carName.setText("car service");
        getContentPane().add(carName);
        carName.setBounds(430, 250, 270, 14);

        attendeesNo.setText("jLabel9");
        getContentPane().add(attendeesNo);
        attendeesNo.setBounds(430, 190, 200, 14);

        theTwo.setFont(new java.awt.Font("Trajan Pro 3", 0, 11)); // NOI18N
        theTwo.setText("jLabel5");
        getContentPane().add(theTwo);
        theTwo.setBounds(350, 120, 240, 11);

        foodset.setText("foosd set");
        getContentPane().add(foodset);
        foodset.setBounds(430, 210, 210, 14);

        theDate.setText("Date");
        getContentPane().add(theDate);
        theDate.setBounds(430, 170, 150, 14);

        jLabel7.setText("Food Set:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 210, 80, 14);

        jLabel10.setText("Car Service:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 250, 80, 14);

        jLabel6.setText("Date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 170, 80, 14);

        jLabel9.setText("The Cake:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 230, 80, 14);

        theCake.setText("cake");
        getContentPane().add(theCake);
        theCake.setBounds(430, 230, 240, 14);

        loc.setText("location");
        getContentPane().add(loc);
        loc.setBounds(430, 150, 240, 14);

        jLabel5.setText("Venue:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 150, 80, 14);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        jLabel3.setText("P");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 350, 10, 23);

        jLabel4.setFont(new java.awt.Font("Vrinda", 0, 11)); // NOI18N
        jLabel4.setText("_________________________________________");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 120, 280, 20);

        total.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        total.setText("jLabel4");
        getContentPane().add(total);
        total.setBounds(270, 350, 140, 20);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        jLabel2.setText("The Total");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 320, 90, 20);

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 400, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\4405875-wedding-background-images.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-270, 0, 1000, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String date = theDate.getText();
       JOptionPane.showMessageDialog(null, "Thank you & see you on " + date);
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendeesNo;
    private javax.swing.JLabel carName;
    private javax.swing.JLabel foodset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loc;
    private javax.swing.JLabel theCake;
    private javax.swing.JLabel theDate;
    private javax.swing.JLabel theTwo;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
