/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class fourth extends javax.swing.JFrame {

    /**
     * Creates new form fourth
     */
    
    private boolean radioText;
    
    private void buttongroup(){
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(set1);
        bg.add(set2);
        bg.add(set3);
        set1.setSelected(true);


       
    }
    
    public fourth() {
        initComponents();
        setVisible(true);
        setTitle("Foods & Beverages");
        setSize(717, 480);
        setResizable(false);
        buttongroup();
        Choice.setVisible(false);
        String radioText = "";
        if (set1.isSelected())
        {
            radioText = set1.getText();
            Choice.setText("Seafood Set");
        }
        else if (set2.isSelected())
        {
            radioText = set2.getText();
            Choice.setText("Chicken Set");
        }
        else if (set3.isSelected())
        {
            radioText = set3.getText();
            Choice.setText("Beef Set");
        }
        
       
        
        
    }
    public void getData3(String theB2, String theG2, String total2, String month, String day, String year, String loc, String Person){
    
    total.setText(total2);
    mr.setText(theG2);
    ms.setText(theB2);
    themonth.setText(month);
    theday.setText(day);
    theyear.setText(year);
    theloc.setText(loc);
    persons.setText(Person);
    mr.setVisible(false);
    ms.setVisible(false);
    themonth.setVisible(false);
    theday.setVisible(false);
    theyear.setVisible(false);
    theloc.setVisible(false);
    persons.setVisible(false);
           
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        themonth = new javax.swing.JLabel();
        theday = new javax.swing.JLabel();
        theyear = new javax.swing.JLabel();
        theloc = new javax.swing.JLabel();
        Choice = new javax.swing.JLabel();
        mr = new javax.swing.JLabel();
        ms = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        persons = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        set3 = new javax.swing.JRadioButton();
        set1 = new javax.swing.JRadioButton();
        set2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/wood.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        themonth.setText("month");
        getContentPane().add(themonth);
        themonth.setBounds(320, 30, 30, 14);

        theday.setText("day");
        getContentPane().add(theday);
        theday.setBounds(380, 30, 18, 14);

        theyear.setText("year");
        getContentPane().add(theyear);
        theyear.setBounds(450, 30, 22, 14);

        theloc.setText("Location");
        getContentPane().add(theloc);
        theloc.setBounds(510, 30, 40, 14);

        Choice.setText("choice");
        getContentPane().add(Choice);
        Choice.setBounds(510, 60, 80, 14);

        mr.setText("Groom");
        getContentPane().add(mr);
        mr.setBounds(570, 30, 31, 14);

        ms.setText("Bride");
        getContentPane().add(ms);
        ms.setBounds(630, 30, 24, 14);

        jLabel10.setText("<html>\n<body>\n<p>SEAFOOD SET</p>\n<p>This set consists off: </p>\n<p>- Grilled Halibut with Peach and Pepper Salsa</p>\n<p>- Bourbon-Glazed Salmon </p>\n<p>- Southwestern-Style Shrimp Taco Salad</p>\n<p>- Seared Scallops w/ Warm Tuscan Beans</p>\n<p>- Tuna Noodle Casserole</p>\n<p>Drinks </p>\n<p>- Tabarrinin Campo Alla Cerqua Sagrantino</p>\n<p>- Cos Contrada </p>\n\n</body>\n</html>");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 250, 240, 180);

        jLabel11.setText("<html>\n<body>\n<p>CHICKEN SET</p>\n<p>This set consists off: </p>\n<p>- Caprese Chicken</p>\n<p>- Bourbon Chicken</p>\n<p>- Spinach Artichoke Stuffed Chicken</p>\n<p>- Crispy Parmesan Chicken</p>\n<p>- Chicken Finger Sub w/ Cabbage Slaw</p>\n<p>Drinks </p>\n<p>- Venissa Dorona</p>\n<p>- Pieropan Calvarino </p>\n\n</body>\n</html>");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 240, 200, 170);

        jLabel12.setText("<html>\n<body>\n<p>BEEF SET</p>\n<p>This set consists off: </p>\n<p>- Super Fast Beef Hash</p>\n<p>- Alberta Beef Dip Sandwich</p>\n<p>- Smoked Beef Brisket</p>\n<p>- Orange and Ginger Beef</p>\n<p>- Braised Beef Short Ribs</p>\n<p>Drinks </p>\n<p>- Mullan Road Cellars Red Blend</p>\n<p>- VIÑA REAL RESERVA </p>\n\n</body>\n</html>");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(500, 240, 210, 160);

        persons.setText("jLabel15");
        getContentPane().add(persons);
        persons.setBounds(320, 50, 40, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("P");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 430, 20, 17);

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 420, 55, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Set 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 220, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Set 1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 220, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Set 2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 220, 60, 20);

        set3.setBackground(new java.awt.Color(255, 153, 0));
        set3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set3ActionPerformed(evt);
            }
        });
        getContentPane().add(set3);
        set3.setBounds(540, 220, 80, 21);

        set1.setBackground(new java.awt.Color(255, 153, 0));
        set1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set1ActionPerformed(evt);
            }
        });
        getContentPane().add(set1);
        set1.setBounds(80, 220, 80, 21);

        set2.setBackground(new java.awt.Color(255, 153, 0));
        set2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set2ActionPerformed(evt);
            }
        });
        getContentPane().add(set2);
        set2.setBounds(310, 220, 80, 21);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/food 3.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 90, 210, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/Webp.net-resizeimage (2)_1.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 90, 200, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/Webp.net-resizeimage.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 100, 190, 110);

        jLabel2.setText("Total:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 430, 34, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Foods & Beverages");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 290, 50);

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setText("jLabel2");
        getContentPane().add(total);
        total.setBounds(80, 430, 180, 17);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/backround-restaurant-menu_116793.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-10, 0, 830, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set3ActionPerformed

    private void set1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set1ActionPerformed

    private void set2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        sixth six = new sixth();
        String total1 = total.getText();
        String mr1 = mr.getText();
        String ms1 = ms.getText();
        String themonth1 = themonth.getText();
        String theday1 = theday.getText();
        String theyear1 = theyear.getText();
        String theloc1 = theloc.getText();
        String per = persons.getText();
        if(set1.isSelected()){
        Choice.setText("Seafood Set");
        }
        else if(set2.isSelected()){
        Choice.setText("Chicken Set");
        }
        else if(set3.isSelected()){
        Choice.setText("Beef Set");
        }
     
        String chosed = Choice.getText();
        this.setVisible(false);
        six.setVisible(true);
        six.getData(total1, mr1, ms1, themonth1, theday1, theyear1, theloc1, chosed, per);
       
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fourth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Choice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mr;
    private javax.swing.JLabel ms;
    private javax.swing.JLabel persons;
    private javax.swing.JRadioButton set1;
    private javax.swing.JRadioButton set2;
    private javax.swing.JRadioButton set3;
    private javax.swing.JLabel theday;
    private javax.swing.JLabel theloc;
    private javax.swing.JLabel themonth;
    private javax.swing.JLabel theyear;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
