/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import javax.swing.ButtonGroup;

/**
 *
 * @author Maxwell
 */
public class sixth extends javax.swing.JFrame {

    /**
     * Creates new form sixth
     */
    private boolean radioText;
    private void buttonGroup(){
    ButtonGroup bg = new ButtonGroup();
    bg.add(cake1);
    bg.add(cake2);
    bg.add(cake3);
    bg.add(cake4);
    
    
    }
    public sixth() {
        initComponents();
        setVisible(true);
        setTitle("Wedding Cake");
        setSize(717, 480);
        setResizable(false);
        cake.setVisible(false);
        price.setVisible(false);
        buttonGroup();
        String radioText = "";
        if (cake1.isSelected())
        {
            radioText = cake1.getText();
        }
        if (cake2.isSelected())
        {
            radioText = cake2.getText();
        }
        if (cake3.isSelected())
        {
            radioText = cake3.getText();
        }
        if (cake4.isSelected())
        {
            radioText = cake4.getText();
        }
    }
    public void getData(String total1, String mr1, String ms1, String themonth1, String theday1, String theyear1, String theloc1, String chosed, String per){
    
        total.setText(total1);
        bride.setText(ms1);
        groom.setText(mr1);
        month.setText(themonth1);
        day.setText(theday1);
        year.setText(theyear1);
        location.setText(theloc1);
        setchosed.setText(chosed);
        person.setText(per);
        bride.setVisible(false);
        groom.setVisible(false);
        month.setVisible(false);
        day.setVisible(false);
        year.setVisible(false);
        location.setVisible(false);
        setchosed.setVisible(false);
        person.setVisible(false);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groom = new javax.swing.JLabel();
        bride = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        setchosed = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cake = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        cake1 = new javax.swing.JRadioButton();
        cake2 = new javax.swing.JRadioButton();
        cake3 = new javax.swing.JRadioButton();
        cake4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        person = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        groom.setText("groom");
        getContentPane().add(groom);
        groom.setBounds(110, 380, 30, 14);

        bride.setText("bride");
        getContentPane().add(bride);
        bride.setBounds(180, 380, 24, 14);

        month.setText("jLabel15");
        getContentPane().add(month);
        month.setBounds(240, 380, 40, 14);

        day.setText("jLabel16");
        getContentPane().add(day);
        day.setBounds(320, 380, 40, 14);

        year.setText("jLabel17");
        getContentPane().add(year);
        year.setBounds(380, 380, 40, 14);

        location.setText("loaction");
        getContentPane().add(location);
        location.setBounds(460, 380, 37, 14);

        setchosed.setText("setChosed");
        getContentPane().add(setchosed);
        setchosed.setBounds(530, 380, 51, 14);

        jLabel11.setText("Total:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 430, 34, 20);

        cake.setText("cake");
        getContentPane().add(cake);
        cake.setBounds(40, 380, 22, 14);

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setText("jLabel2");
        getContentPane().add(total);
        total.setBounds(80, 430, 180, 17);

        cake1.setText("P 6,300");
        cake1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cake1ActionPerformed(evt);
            }
        });
        getContentPane().add(cake1);
        cake1.setBounds(30, 300, 110, 23);

        cake2.setText("P 5,000");
        getContentPane().add(cake2);
        cake2.setBounds(200, 300, 110, 23);

        cake3.setText("P 5,500");
        getContentPane().add(cake3);
        cake3.setBounds(350, 300, 110, 23);

        cake4.setText("P 5,000");
        getContentPane().add(cake4);
        cake4.setBounds(530, 300, 120, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("P");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 430, 20, 17);

        price.setText("jLabel12");
        getContentPane().add(price);
        price.setBounds(250, 410, 40, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\cake 1.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 30, 170, 250);

        person.setText("jLabel13");
        getContentPane().add(person);
        person.setBounds(190, 350, 40, 14);

        jLabel10.setText("\"Strawberry filled Strawberry Cake\"");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 280, 190, 14);

        jLabel8.setText("\"White Chocolate WC\"");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 280, 140, 14);

        jLabel9.setText("\"Mocha Infused White Chocolate\"");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 280, 190, 14);

        jLabel7.setText("\"The Triple Chocolate WC\"");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 140, 14);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 420, 55, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\cake 5.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 50, 190, 230);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\cake 4.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 50, 170, 220);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maxwell\\Downloads\\cake 3.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 50, 160, 220);

        jLabel2.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel2.setText("Wedding Cakes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/cake bckgrnd.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-830, 0, 1640, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cake1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cake1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cake1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fifth f = new fifth();
        f.setVisible(true);
        this.setVisible(false);
        
        String t = total.getText();
        String b = bride.getText();
        String g = groom.getText();
        String l = location.getText();
        String m = month.getText();
        String d = day.getText();
        String y = year.getText();
        String c = setchosed.getText();
        String a = person.getText();
        if(cake1.isSelected()){
        cake.setText("The Triple Chocolate WC");
        price.setText("6300");
        }
        else if(cake2.isSelected()){
        cake.setText("White Chocolate WC");
        price.setText("5000");
        }
        else if(cake3.isSelected()){
        cake.setText("Mocha Infused White Chocolate");
        price.setText("5500");
        }
        else if(cake4.isSelected()){
        cake.setText("Strawberry-filled Strawberry Cake");
        price.setText("5000");}
        String p = price.getText();
        String cakechosed = cake.getText();
        f.getData4(t, b, g, l, m, d, y,c, cakechosed, p, a);
   
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sixth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bride;
    private javax.swing.JLabel cake;
    private javax.swing.JRadioButton cake1;
    private javax.swing.JRadioButton cake2;
    private javax.swing.JRadioButton cake3;
    private javax.swing.JRadioButton cake4;
    private javax.swing.JLabel day;
    private javax.swing.JLabel groom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel location;
    private javax.swing.JLabel month;
    private javax.swing.JLabel person;
    private javax.swing.JLabel price;
    private javax.swing.JLabel setchosed;
    private javax.swing.JLabel total;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
