/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp1;

import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class third extends javax.swing.JFrame {

    /**
     * Creates new form third
     */
    public third() {
        initComponents();
        setVisible(true);
        setTitle("Date & Location");
        setSize(480,480);
        setResizable(false);
        p.setVisible(false);
        
        
    }
    
    public void  getName2(String bride, String groom, String thePersons){
        theB.setText(bride);
        theG.setText(groom);
        p.setText(thePersons);
        
    }
    
    public void getVals(int vals){
     
        double result = vals * 1000;
        if (vals <= 250 ){
        total.setText(Double.toString(result));}
        else if(vals >= 250 && vals <= 300){
        total.setText(Double.toString(result - result *.05));
        }
        else if(vals >= 301 && vals <= 550){
        total.setText(Double.toString(result - result * .20));
        }
        else if(vals >= 550 && vals <= 1000){
        total.setText(Double.toString(result - result * .25));
        }
        else if(vals >= 1000 && vals <= 1200){
        total.setText(Double.toString(result - result * .30));
        }
        else if(vals >= 1200 && vals <= 1500){
        total.setText(Double.toString(result - result * .50));
        }
        else if (vals > 1500){
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "We're sorry, the maximum person is 1500 only.");
        System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        l = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m = new javax.swing.JComboBox<>();
        d = new javax.swing.JComboBox<>();
        y = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        theB = new javax.swing.JLabel();
        theG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setText("Month");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 60, 14);

        l.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasay", "Tagaytay", "Q.C", "Metro Manila", "Taguig", "Cainta", "Mandaluyong" }));
        getContentPane().add(l);
        l.setBounds(20, 240, 190, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("P");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 420, 20, 17);

        p.setText("jLabel11");
        getContentPane().add(p);
        p.setBounds(300, 80, 40, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Select Location");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 210, 100, 14);

        jLabel7.setText("Day");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 140, 60, 14);

        jLabel8.setText("Year");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 140, 60, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Select Schedule");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 120, 100, 14);

        m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan\t", "Feb", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(20, 160, 70, 20);

        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(d);
        d.setBounds(100, 160, 50, 20);

        y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019" }));
        getContentPane().add(y);
        y.setBounds(160, 160, 70, 20);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 410, 55, 23);

        theB.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        theB.setText("jLabel5");
        getContentPane().add(theB);
        theB.setBounds(20, 30, 100, 25);

        theG.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        theG.setText("jLabel6");
        getContentPane().add(theG);
        theG.setBounds(130, 30, 100, 25);

        jLabel3.setFont(new java.awt.Font("Trajan Pro 3", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("The Bride");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 80, 11);

        jLabel4.setFont(new java.awt.Font("Trajan Pro 3", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("The Groom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 10, 100, 14);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Total:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 400, 34, 14);

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(240, 240, 240));
        total.setText("jLabel2");
        getContentPane().add(total);
        total.setBounds(30, 420, 180, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp1/Beautiful-Hearts-HD-Wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-80, -10, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fourth f = new fourth();
        f.setVisible(true);
        String total2 = total.getText();
        String theB2 = theB.getText();
        String theG2 = theG.getText();
        String month = m.getSelectedItem().toString();
        String day = d.getSelectedItem().toString();
        String year = y.getSelectedItem().toString();
        String loc = l.getSelectedItem().toString();
        String Person = p.getText();
        
        f.getData3(theB2, theG2, total2, month, day, year, loc, Person);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    
    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(third.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new third().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> l;
    private javax.swing.JComboBox<String> m;
    private javax.swing.JLabel p;
    private javax.swing.JLabel theB;
    private javax.swing.JLabel theG;
    private javax.swing.JLabel total;
    private javax.swing.JComboBox<String> y;
    // End of variables declaration//GEN-END:variables
}
