
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maxwell
 */
public class grade extends javax.swing.JFrame {

    /**
     * Creates new form grade
     */
    public grade() {
        initComponents();
        setTitle("Midterm");
        setSize(309, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prelim = new javax.swing.JTextField();
        midterm = new javax.swing.JTextField();
        finals = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Prelim");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 59, 70, 14);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Midterm");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 97, 80, 14);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Finals");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 135, 80, 14);

        prelim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prelimKeyTyped(evt);
            }
        });
        getContentPane().add(prelim);
        prelim.setBounds(115, 56, 135, 20);

        midterm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                midtermKeyTyped(evt);
            }
        });
        getContentPane().add(midterm);
        midterm.setBounds(115, 94, 135, 20);

        finals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                finalsKeyTyped(evt);
            }
        });
        getContentPane().add(finals);
        finals.setBounds(115, 132, 135, 20);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(115, 180, 140, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-160, 0, 560, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String prelims, midterms, finalGrade;
        prelims = prelim.getText();
        midterms = midterm.getText();
        finalGrade = finals.getText();
        
        double grade = (Double.parseDouble(prelims)*.3 + Double.parseDouble(midterms)*.3 + Double.parseDouble(finalGrade)*.4);
        
        if(grade >= 75 )
        {JOptionPane.showMessageDialog(null, ":) Grade :" + grade);}
        else
            JOptionPane.showMessageDialog(null, ":( Grade :" + grade);
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prelimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prelimKeyTyped
        // TODO add your handling code here:
        
                char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
            
        }
      
    }//GEN-LAST:event_prelimKeyTyped

    private void midtermKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midtermKeyTyped
        // TODO add your handling code here:
                      char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
            
        }
    }//GEN-LAST:event_midtermKeyTyped

    private void finalsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finalsKeyTyped
        // TODO add your handling code here:
                      char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
            
        }
    }//GEN-LAST:event_finalsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField finals;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField midterm;
    private javax.swing.JTextField prelim;
    // End of variables declaration//GEN-END:variables
}
